### ISSUE TITLE
scrollIntoView parameters

### ISSUE THREAD

**Issue by DylanPiercey** [yoshuawuyts/scroll-to-anchor#1]
Would you accept a PR that allowed for a configurable [parameters](https://developer.mozilla.org/en/docs/Web/API/Element/scrollIntoView#Parameters)?  This would allow smooth scrolling and such.

**Comment by yoshuawuyts** [comment]
Oh cool, yeah!

**Comment by DylanPiercey** [comment]
Pr got merged, but this never got closed. Going to close it now, thanks!
